name: final_project_news_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  d_input: ^2.0.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
