name: final_project_news_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0-93.1.beta

dependencies:
  d_input: ^2.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  get_it: ^9.2.0
  google_fonts: ^6.3.3
  hive: ^2.2.3
  hive_ce: ^2.15.1
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
